version: '3'

services:
  api:
    build: .
    container_name: nest
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./app:/app
    depends_on:
      - dev-db
    links:
      - dev-db
    restart: always

  dev-db:
    image: postgres:14
    container_name: pgdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  test-db:
    image: postgres:14
    container_name: pgdb-test
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
